---
# Configure firewall

- name: Ensure http port is open
  firewalld:
    zone: "{{firewall_zone}}"
    service: http
    permanent: yes
    state: enabled
  notify: reload firewalld
  tags: ['nginx']

- name: Ensure https port is open
  firewalld:
    zone: "{{firewall_zone}}"
    service: https
    permanent: yes
    state: enabled
  notify: reload firewalld
  tags: ['nginx']

