---
# Install software on SUSE Linux variants


- name: Ensure LEMP software is installed
  package:
    name: "{{ lemp_packages }}"
    state: present
  tags: ['nginx','php','mariadb']
- name: Ensure apcu memcache is installed
  package:
    name: "{{ apcu_packages }}"
    state: present
  tags: ['php','memcache']
  when: apcu_enable == true
  notify: restart php-fpm
- name: Ensure modules for MediaWiki are installed
  package:
    name: "{{ mediawiki_packages }}"
    state: present
  tags: ['php','mediawiki']
  when: mediawiki == true
  notify: restart php-fpm
- name: Ensure modules for NextCloud are installed
  package:
    name: "{{ nexcloud_packages }}"
    state: present
  tags: ['php','nextcloud']
  when: nextcloud == true
  notify: restart php-fpm
- name: Ensure modules for Lychee are installed
  package:
    name: "{{ lychee_packages }}"
    state: present
  tags: ['php','lychee']
  when: lychee == true
  notify: restart php-fpm
  
