---
# tasks file for lempo

 
- name: include distribution specific vars
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
#- name: include distribution specific install
#  include: "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"

- include: install.yml
- include: mariadb.yml
- include: php.yml
- include: firewall.yml
  when: config_firewall == true
- include: default-page.yml
  when: setup_default_page == true
