---
# Configure php

- name: Ensure php.ini is configured
  template:
    src: php.ini.j2
    dest: /etc/php7/cli/php.ini
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  tags: ['php']

- name: Ensure php-fpm.conf is configured
  template:
    src: php-fpm.conf.j2
    dest: /etc/php7/fpm/php-fpm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  tags: ['php']

- name: Ensure www.conf is configured
  template:
    src: www.conf.j2
    dest: /etc/php7/fpm/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm
  tags: ['php']

- name: Ensure php-fpm is enabled
  systemd:
    name: php-fpm
    state: started
    enabled: yes
  tags: ['php']
